image: gitpod/workspace-yugabytedb
tasks:
  - name: streaming
    before: gp sync-await before
    init: gp sync-await init
    command: |
      cd mastodon
      BIND=0.0.0.0 PORT=8008 node ./streaming
  - name: sidekiq
    before: |
      gp sync-await before
      redis-server --daemonize yes
    init: gp sync-await init
    command: |
      cd mastodon
      RAILS_ENV=production DB_POOL=5 bundle exec sidekiq -c 5
  - name: web
    before: |
      mkdir -p /workspace/.rvm
      rvm install 3.0.4
      rvm use 3.0.4
      brew install libidn redis
      if [ -z "$GITTAG" ]; then export GITTAG=main; fi
      gp sync-done before
    init: |
      git clone -b "$GITTAG" https://github.com/mastodon/mastodon.git
      echo "$RUBY_VERSION" | cut -d- -f2 > mastodon/.ruby-version
      cd mastodon
      git checkout "$GITTAG"
      bundle config --local build.idn-ruby --with-idn-dir="$(brew --prefix libidn)"
      bundle install
      yarn install
      echo "LOCAL_DOMAIN=$(gp url 8080 | cut -d/ -f3)" > .env.production
      cat ../.env.production.example >> .env.production
      echo "SMTP_FROM_ADDRESS=notifications@$(gp url 8080 | cut -d/ -f3)" >> .env.production
      echo "SECRET_KEY_BASE=$(RAILS_ENV=production bundle exec rake secret)" >> .env.production
      echo "OTP_SECRET=$(RAILS_ENV=production bundle exec rake secret)" >> .env.production
      RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key >> .env.production
      # wait until YSQL is available, create the database and utility function
      until ysqlsh <<<'
       create database mastodon;\c mastodon
       create or replace function array_signature(a bigint[])
       returns text as $$
       select array_agg(unnest order by unnest)::text
       from unnest(a);
       $$ immutable language sql;
       ' ; do sleep 1 ; done 2>/dev/null
      # remove indexes that are not supported
      sed -e '/"index_unique_conversations"/d' -i db/schema.rb
      sed -e '/"index_ip_blocks_on_ip"/d' -i db/schema.rb
      # create the database
      RAILS_ENV=production rails --trace db:setup
      # add indexes with DDL (this may be done from schema.rb)
      ysqlsh -e -c '
       CREATE UNIQUE INDEX index_unique_conversations ON public.account_conversations 
       (account_id, conversation_id, (array_signature(participant_account_ids)));
       ' mastodon
      # end modifications for YugabyteDB
      RAILS_ENV=production rails assets:precompile
      RAILS_ENV=production bin/tootctl accounts create a --email "admin@$(gp url 8080 | cut -d/ -f3)" --confirmed --role admin
      # create five users to play with conversations
      for i in {1..5} ; do 
       email="admin$i@$(gp url 8080 | cut -d/ -f3)" 
       echo Password for "$email" is: $(RAILS_ENV=production bin/tootctl accounts create admin$i --email "$email" --confirmed --role Admin )
       done
      cd ..
      gp sync-done init
    command: |
      cd mastodon
      RAILS_ENV=production BIND=0.0.0.0 PORT=8080 RAILS_SERVE_STATIC_FILES=true bundle exec puma -C config/puma.rb
ports:
  - port: 8080
    visibility: public
    onOpen: open-preview
  - port: 8008
    onOpen: ignore
  - port: 5433
    onOpen: ignore
  - port: 7000
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 12000
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 6379
    onOpen: ignore
vscode:
  extensions:
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
